### ISSUE TITLE
Error While Running The App

### ISSUE THREAD

**Issue by thekevincoutinho** [EOSIO/eosio-swift-ios-example-app#30]
**Error**
2020-12-02 11:45:42.937795+0800 
EosioSwiftiOSExampleApp[8634:134314] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed

**Simulator Screenshot - Does not show balance**
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-02 at 11 52 29](https://user-images.githubusercontent.com/62196822/100826278-ed8a4c80-3494-11eb-917b-b027aaf7614a.png)

**ViewController.swift Code Changes Section**

    let endpoint = URL(string: "https://localhost:8888")! // override with node endpoint URL
    
    // KC - Use EOS Studio To Supply The Private Key
    let privateKeys = ["5HsA9z7GAfqaU8mnZFh8DNoa4pMdNvSTkES61kpLTb6ZxVmwobj"]
    let currencySymbol = "SYS" // override to the token of your choice (e.g., "EOS")
    let permission = "active" // override if needed

    // Transfer action data variables
    // KC - Edited the from and to
    let from = "kevincou"
    let to = "eosio"
    let quantity = "1.0000 SYS" // override if needed (e.g., "1.0000 EOS")
    let memo = "" // override if needed

**Comment by thekevincoutinho** [comment]
@opi-smccoole Please help!

**Comment by opi-smccoole** [comment]
The error shown is generally accepted to be the result of a simulator bug in Xcode 12 when using any of the iOS 14 instances and generally not the cause of the application not working.  That means that there is likely additional information in the Xcode console that will be needed to diagnose the issue.  Additional helpful information would include:

- What blockchain are you using?
- What smart contracts?
- Are you sure the blockchain setup is complete and accurate?  i.e. user created, keys loaded, etc.

One thing you could try immediately is to use the local IP address of the machine in place of `localhost` in your endpoint. 

`let endpoint = URL(string: "https://10.0.0.35:8888")!`

Substituting your own IP address in place of the example one.

**Comment by thekevincoutinho** [comment]
> The error shown is generally accepted to be the result of a simulator bug in Xcode 12 when using any of the iOS 14 instances and generally not the cause of the application not working. That means that there is likely additional information in the Xcode console that will be needed to diagnose the issue. Additional helpful information would include:
> 
> * What blockchain are you using?
> * What smart contracts?
> * Are you sure the blockchain setup is complete and accurate?  i.e. user created, keys loaded, etc.
> 
> One thing you could try immediately is to use the local IP address of the machine in place of `localhost` in your endpoint.
> 
> `let endpoint = URL(string: "https://10.0.0.35:8888")!`
> 
> Substituting your own IP address in place of the example one.

Got it!! Thanks heaps mate!
